### ISSUE TITLE
Remove dependency on errwrap

### ISSUE THREAD

**Issue by jen20** [joyent/triton-go#10]
We are currently using the HashiCorp `errwrap` library - this is unnecessary since we only need a tiny subset of the functionality.

**Comment by sean-** [comment]
Nuking `errwrap`++.

Bumping this issue given the fun we had on this topic this week.

**Comment by sean-** [comment]
After #90 , are we g2g to close this issue out?

**Comment by stack72** [comment]
Nope - still got #91 and then the compute package!
