### ISSUE TITLE
compute/instances: Support for tags as a filter when using the `List` method to list machines.

### ISSUE THREAD

**Issue by kwilczynski** [joyent/triton-go#115]
Currently, the `List` method (see: [instances.go#L162](https://github.com/joyent/triton-go/blob/master/compute/instances.go#L162)) does not seem to fully support passing tags as a possible filter, even when the `Tags` field from the `ListInstancesInput` type (see: [instances.go#L156](https://github.com/joyent/triton-go/blob/master/compute/instances.go#L156)) is populated with the values in the right format (see below), there isn't anything that uses the `Tags` field when the query string is being assembled, therefore no filter based on tags can currently be applied.

Since tags can also serve as a filter to narrow down the list of machines when querying the CloudAPI (see: [ListMachines](https://apidocs.joyent.com/cloudapi/#ListMachines)), and so it would be nice to support tags correctly, especially from the CLI users point of view passing something like e.g. `--tags='[name=test,type=anything,answer=42]'`, etc.

The CloudAPI takes a list of strings formatted as `tag.<NAME>=<VALUE>` - albeit, asking client users to provide strings like that manually seem awkward, and I was thinking that we could abstract setting and returning tags through a common type, for example:

```golang
type Tag struct {
    Key   string
    Value string
}
```

And a list of tags would simply be a slice/list of type `Tag`. This would also possibly reduce the differences when the client returns tags - sometimes as `map[string]string` and other times as `map[string]interface{}`.

**Comment by kwilczynski** [comment]
There is a lot of work being done on the Triton CLI implementation in the [trition-cli](https://github.com/joyent/triton-go/tree/triton-cli) branch, which is where the ability to filter based on tags could be useful.

**Comment by kwilczynski** [comment]
Related https://github.com/joyent/triton-go/pull/116.

**Comment by kwilczynski** [comment]
The Pull Request https://github.com/joyent/triton-go/pull/116, adds the missing support.

Work on adding the `Tag` type would be move involved (e.g. return values, etc.), thus it would come later.

**Comment by kwilczynski** [comment]
Related https://github.com/joyent/triton-go/issues/12.

**Comment by twhiteman** [comment]
This seems to have been fixed in #116.
