### ISSUE TITLE
Challenge of handling Go zero-values correctly inside input types.

### ISSUE THREAD

**Issue by kwilczynski** [joyent/triton-go#122]
Related to https://github.com/joyent/triton-go/pull/119#issuecomment-366793077.

As per the linked comment (see above) there are a number of challenges related to Go basic types such having default zero-values (e.g. `bool` type is `false`) when used as a input struct members.

Possible issues:

- Handling an empty string that was purposely passed as such

Not a very common use case, and blank strings might be excluded by CloudAPI anyway.

- Working with an integer value of 0

A possible use case might be setting ICMP type 0 ("Echo Reply") as a valid code type when setting a firewall rule.

- Working with boolean values which can be explicitly either `true` or `false`

Similarly to the problem outlined in the linked comment (see above) setting a value (a toggle?) to either `true` or `false` to use when building a filter to narrow down results.

This is a potentially non-trivial problem to solve, as it might require us to leverage pointers (similarly to the AWS SDK, for example) in order to check whether a pointer is not-nil and then dereference it to check the actual value, which would potentially change the current API contract we already have with the consumers of the Triton Go client. It might also require a set of helper methods to be added to safeguard any interactions users might have when setting and/or getting values from out types (something akin to `aws.String()`, etc.).

A discussion around why AWS SDK decided to go this route alongside explanation of some use cases can be read in the following issue: https://github.com/aws/aws-sdk-go/issues/363.

Alternative approach, might be to provide a set of helper function for each of the type, as per suggestion from Sean in the following issue: https://github.com/joyent/triton-go/issues/104. Such approach (Note: both setting and accessing values would require something akin to "getters" and "setters" to be provided; similarly to the example from the linked issue) would add some complexity (more code to maintain) but it is probably the most convenient to use from point of view (albeit, this is a matter of debate as a lot of boiler-plate is not good either).

**Comment by kwilczynski** [comment]
Hi @stack72, @cheapRoc and @sean-, this is an RFC-style issue, and I need your insight on the matter. What do you think would be the best way going forward? I might also be completely wrong about the whole problem.

Thank you for help in advance!

**Comment by cheapRoc** [comment]
The biggest problem I've seen in the past is where we exclude an `input.ID` from CloudAPI URL generation and receive an incorrect HTTP method error because we're hitting an entirely different API endpoint.

That would be the kind of examples we would need to clarify what and where we are making fixes for existing downstream consumers, of which we have many now.

I think AWS had the right idea using pointers for input field values so I'd probably prefer that. This sums it up well.

> The SDK uses pointers for all primitive and struct type fields. In many cases the type's Zero value of a field has meaning, and is different from unset, and a non zero value. All API fields in Input and Output structs are pointers, because even though a field is required today, it may not be required in the future.

**Comment by kwilczynski** [comment]
HI @cheapRoc, thank you!

Especially the `In many cases the type's Zero value of a field has meaning, and is different from unset, and a non zero value.` was a cause of a lot of rather interesting issues in Terraform (the aforementioned ICMP type 0 handling in Security Groups and NACLs), as the model/struct it uses to define a resource suffers from the same problem as the AWS' SDK (anecdotally, Packer opted for allowing pointers, which solved a lot of edge cases for them).

**Comment by cheapRoc** [comment]
Yes, and I should add that I concur with some of the feedback in the AWS thread that trying to solve the zero value/unset problem with methods would introduce API breakage for fast moving backend service APIs, of which I'm sure we'll have plenty.
