### ISSUE TITLE
Overriding HTTP signing using custom HTTP headers

### ISSUE THREAD

**Issue by cheapRoc** [joyent/triton-go#124]
In order to satisfy integration with SSO and other authentication processes we need to have more control over how we sign HTTP requests. 

Authentication with CloudAPI is handled by our SSH key signing of a few HTTP headers, primarily `date` and `Authorization`. Both of these are generated during any of the four `ExecuteRequest` funcs within the client package. We need a way to manually set those headers and not have them pre-generated for us automatically.

I'm open to suggestions on where and how we perform this customization but my current idea is to open up customization of HTTP headers at the client level.

1. We introduce a struct field called `Client.RequestHeaders`.
2. Attach a method to all sub-package clients called `SetHeaders` which allows us to pass in an `http.Header` object. We'll use `account.AccountClient` as an example.
3. `AccountClient.SetHeaders` will set `Client.Headers`.
4. `Client.Headers` will be used to override any HTTP headers set by the `Client.ExecuteRequest` methods before the actual backend `net/http` request is made to CloudAPI.
5. A `defer` function should be called that flushes the `http.Header` object from `Client` upon the request being made.

Thoughts? Am I missing something that could come up with concurrent calls?

/cc @sean- @stack72 @kwilczynski

**Comment by cheapRoc** [comment]
Since this was relatively easy to add I went ahead and made the changes to satisfy what I'm working on. With the defer cleaning up after every request I'm not seeing custom headers on subsequent backend API calls. I'll post a PR up when I know this satisfies my remaining requirements for TSG auth.

**Comment by kwilczynski** [comment]
Hi @cheapRoc! Apologies for a bit of a late reply :(

What I was thinking about introducing a concept of an authentication middleware. An interface that would allow us to implement different authentication schemas e.g., CloudAPI, CMON, TSG, SSO (via Oauth/Oauth2?) as long as said interface is implemented. The idea here was to enable each of the different modes of authenticating with something specific to them, but transparently, for example: CMON might benefit from in-memory caching of the self-signed certificate it needs upon generating one from the SSH private key; Oauth could have facility to automatically refresh access tokens using refresh tokens (if such are present), etc.

I am not sure how popular is such notion of an authentication middleware for clients/SDKs contrary to servers, thus it might be a completely silly idea.

**Comment by cheapRoc** [comment]
Those are fair enough suggestions but I think they're premature. While client side middleware would definitely help implement a number of authentication schemes, we don't have any others besides the HTTP request signing. While I wish [sdcsso](http://github.com/joyent/sdcsso) was using something common like OAuth, it seems to be rehashing HTTP signing which is why overriding headers should give us what we need for the moment.

But client side middleware should definitely be noted if we need it in the future.

> I am not sure how popular is such notion of an authentication middleware for clients/SDKs contrary to servers, thus it might be a completely silly idea.

[Faraday](https://github.com/lostisland/faraday#advanced-middleware-usage) comes to mind, I'm sure there are others and in Go.

**Comment by kwilczynski** [comment]
Hi @cheapRoc,

Ah I see!

Sadly, I couldn't see https://github.com/joyent/sdcsso (and hence I wrongly assumed it would be something akin to Oauth, etc.) as it's private, but everything you've said makes sense, given how it works.

I did a quick search on Joyent's GitHub landing page, and found this: https://github.com/joyent/hapi-triton-auth. Is this something close to how the SSO works? (just curious).

**Comment by cheapRoc** [comment]
Whoops, didn't realize it was private, haven't opened it too much. It appears like the hapi plugin is performing a similar integration.

**Comment by stack72** [comment]
Closed via #125
