### ISSUE TITLE
Support for specifying brand=bhyve

### ISSUE THREAD

**Issue by misterbisson** [joyent/triton-go#128]
As implemented in node-triton: https://github.com/joyent/node-triton/commit/26b97b5bedd64dbce51cf470af3c8fdff3cda57c:

> [TRITON-124] add node-triton support for bhyve. This adds a `triton instance create --brand=bhyve ...` option that can be used for zvol images that support it. Note that bhyve support is alpha in TritonDC -- most datacenters won't yet support this option.

**Comment by cheapRoc** [comment]
@misterbisson Was this a recent change to CloudAPI to support `brand` as an option into `CreateMachine`? I don't see a `brand` parameter in CloudAPI's current docs.

**Comment by cheapRoc** [comment]
Never mind, [stumbled onto it](https://github.com/joyent/sdc-cloudapi/commit/03830f8ea379758c13afc9267c8545b4efb59ae3#diff-1a523bd9fa0dbf998008b37579210e12R913).

**Comment by misterbisson** [comment]
I have some concerns about the implementation that I raised (internally) in [triton-124](https://jira.joyent.us/secure/EditComment!default.jspa?id=68056&commentId=183534).

**Comment by stack72** [comment]
There is no support in cloudapi for this as of now

**Comment by misterbisson** [comment]
This, I think can be closed. Please see further discussion in [TRITON-181](https://jira.joyent.us/browse/TRITON-181?focusedCommentId=183925&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-183925), as well as TRITON-190 and TRITON-191.

**Comment by stack72** [comment]
Closed for now - thanks for this @misterbisson
