### ISSUE TITLE
Integrate Manta client

### ISSUE THREAD

**Issue by jen20** [joyent/triton-go#13]
I wrote an initial Manta client based on similar patterns to this library at https://github.com/jen20/manta-go - we should likely merge it into this library to have a single import across all services.

Thoughts, @misterbisson?

**Comment by misterbisson** [comment]
Agreed, having both in a single library seems to have more benefits than problems.

**Comment by misterbisson** [comment]
Heh, @cheapRoc opened https://github.com/joyent/triton-go/issues/9 as well.

**Comment by jen20** [comment]
Closing in favour of #9.
