### ISSUE TITLE
Support using 'network objects' for creating NIC

### ISSUE THREAD

**Issue by siepkes** [joyent/triton-go#139]
When creating a NIC (or instance with a NIC) cloud API supports supplying a network object instead of just a network UUID. Using the network object one can assign a user chosen IPv4 address for fabric networks. See the [CloudAPI docs on network objects](https://apidocs.joyent.com/cloudapi/#network-objects). Main use case for this is supporting applications which don't take kindly to changing IP's when redeployed.

This functionality is needed to implement terraform-providers/terraform-provider-triton#98

Biggest issue with this is probably deciding whether of not this should be implemented as an API breaking change. Currently everything that handles NIC's assume the NIC is just a string. Making a struct of it would break backwards compatibility.

**Comment by Smithx10** [comment]
Just ran into this.  Need this.

**Comment by twhiteman** [comment]
Was added in #158
