### ISSUE TITLE
Handling of metadata, specially for nested objects?

### ISSUE THREAD

**Issue by kwilczynski** [joyent/triton-go#151]
At the moment we assume that a compute instance metadata is a flat key-value pair map - this is true in majority of cases e.g., when setting an arbitrary data, adding user-script, cloud-init configuration, etc.

The remaining, albeit not very often being used, is the case when the `credentials` (see: [CreateMachine](https://apidocs.joyent.com/cloudapi/#CreateMachine) to be requested for a compute instance. In this case, the resulting object can contain a nested object inside the called `credentials`, which would be another key-value map, alongside other key-value pairs already there.

We would not be able to parse such JSON in the response into a proper type (struct) on the Go side, as our metadata handling relies on a `map[string]string` type as per [instances.go](https://github.com/joyent/triton-go/blob/95f55362e2cda0cd450e3dc409fd14765f60d29a/compute/instances.go#L66).

We need to decide how to handle this going forward, and if we want to handle this at all (given the potential lack of use-cases for the credentials generation, etc.).

**Comment by kusor** [comment]
We've moved metadata to the type `map[string]interface{}` for v2 of the package.
