### ISSUE TITLE
Support Network Objects for /AddNIC

### ISSUE THREAD

**Issue by Smithx10** [joyent/triton-go#169]
Currently Triton-GO Supports Creating instances using Network Objects,  but the AddNIC function was not updated also.  

https://github.com/joyent/triton-go/pull/158

**Comment by Smithx10** [comment]
This PR should address this missing functionality.

https://github.com/joyent/triton-go/pull/170

**Comment by twhiteman** [comment]
Thanks - committed in 47e17bc.
