### ISSUE TITLE
License

### ISSUE THREAD

**Issue by tgross** [joyent/triton-go#2]
This repo does not have a LICENSE file. Generally Joyent is using MPL2.0.

However, in https://github.com/docker/distribution/issues/2041#issuecomment-273480408 it's been noted that this license is copyleft and this might raise questions about what projects the library can be reused in.

While the MPL2.0 is probably the best license for our main product lines, this discussion has me questioning whether it's the right license for SDKs like `triton-go`. This has not come up previously because Terraform (the sole consumer of `gomanta` and `gotriton` as far as I know) is itself MPL2.0

cc @misterbisson @bcantrill @jen20

**Comment by tgross** [comment]
[Mozilla's own FAQ describes it that way (see Q12)](https://www.mozilla.org/en-US/MPL/2.0/FAQ/) and I've seen it described as "weak copy-left" in places.

**Comment by jen20** [comment]
As far as I'm aware MPLv2 is the closest thing to the CDDL in common (non-ex-Sun) usage today - it's file based copyleft. Given the usage of this library primarily in Terraform and Packer, which are both MPLv2 license it hasn't been a problem, however I'm in favour of relicensing it as MIT or Apache v2.
