### ISSUE TITLE
Completeness against CloudAPI

### ISSUE THREAD

**Issue by cheapRoc** [joyent/triton-go#25]
The following was extracted from the old README. We can track these as a single issue moving forward.

- Accounts
    - [x] GetAccount
    - [x] UpdateAccount
- Keys
    - [x] ListKeys
    - [x] GetKey
    - [x] CreateKey
    - [x] DeleteKey
- Users
    - [x] ListUsers
    - [x] GetUser
    - [x] CreateUser
    - [x] UpdateUser
    - [ ] ChangeUserPassword
    - [x] DeleteUser
- Roles
    - [x] ListRoles
    - [x] GetRole
    - [x] CreateRole
    - [x] UpdateRole
    - [x] DeleteRole
- Role Tags
    - [ ] SetRoleTags
- Policies
    - [x] ListPolicies
    - [x] GetPolicy
    - [x] CreatePolicy
    - [x] UpdatePolicy
    - [x] DeletePolicy
- User SSH Keys
    - [x] ListUserKeys
    - [x] GetUserKey
    - [x] CreateUserKey
    - [x] DeleteUserKey
- Config
    - [x] GetConfig
    - [x] UpdateConfig
- Datacenters
    - [x] ListDatacenters
    - [x] GetDatacenter
- Services
    - [x] ListServices
- Images
    - [x] ListImages
    - [x] GetImage
    - [x] DeleteImage
    - [x] ExportImage
    - [x] CreateImageFromMachine
    - [x] UpdateImage
- Packages
    - [x] ListPackages
    - [x] GetPackage
- Instances
    - [x] ListMachines
    - [x] GetMachine
    - [x] CreateMachine
    - [x] StopMachine
    - [x] StartMachine
    - [x] RebootMachine
    - [x] ResizeMachine
    - [x] RenameMachine
    - [x] EnableMachineFirewall
    - [x] DisableMachineFirewall
    - [x] CreateMachineSnapshot
    - [x] StartMachineFromSnapshot
    - [x] ListMachineSnapshots
    - [x] GetMachineSnapshot
    - [x] DeleteMachineSnapshot
    - [x] UpdateMachineMetadata
    - [x] ListMachineMetadata
    - [x] GetMachineMetadata
    - [x] DeleteMachineMetadata
    - [x] DeleteAllMachineMetadata
    - [x] AddMachineTags
    - [x] ReplaceMachineTags
    - [x] ListMachineTags
    - [x] GetMachineTag
    - [x] DeleteMachineTag
    - [x] DeleteMachineTags
    - [x] DeleteMachine
    - [ ] MachineAudit
- Firewall Rules
    - [x] ListFirewallRules
    - [x] GetFirewallRule
    - [x] CreateFirewallRule
    - [x] UpdateFirewallRule
    - [x] EnableFirewallRule
    - [x] DisableFirewallRule
    - [x] DeleteFirewallRule
    - [x] ListMachineFirewallRules
    - [x] ListFirewallRuleMachines
- Fabrics
    - [x] ListFabricVLANs
    - [x] CreateFabricVLAN
    - [x] GetFabricVLAN
    - [x] UpdateFabricVLAN
    - [x] DeleteFabricVLAN
    - [x] ListFabricNetworks
    - [x] CreateFabricNetwork
    - [x] GetFabricNetwork
    - [x] DeleteFabricNetwork
- Networks
    - [x] ListNetworks
    - [x] GetNetwork
- Nics
    - [X] ListNics
    - [X] GetNic
    - [x] AddNic
    - [x] RemoveNic

**Comment by cheapRoc** [comment]
In lieu of a more formal change log, I've checked off completeness of the Metadata API.

- ListMachineMetadata
- GetMachineMetadata
- DeleteMachineMetadata
- DeleteAllMachineMetadata

**Comment by stack72** [comment]
All of the Users func has been added in #53 :)

**Comment by cheapRoc** [comment]
Checked off `RebootMachine` support.

**Comment by cheapRoc** [comment]
Removed the following since we won't support them...

- ~~Analytics~~
    - DescribeAnalytics
    - ListInstrumentations
    - GetInstrumentation
    - GetInstrumentationValue
    - GetInstrumentationHeatmap
    - GetInstrumentationHeatmapDetails
    - CreateInstrumentation
    - DeleteInstrumentation

**Comment by stack72** [comment]
Checked off *ListRulesMachines

**Comment by stack72** [comment]
@cheapRoc there is a PR that adds all Policies* additions

That takes us to 89 / 92 :)

**Comment by cheapRoc** [comment]
I've created three separate issue for the remaining tasks. I'm ok with closing this now.

🎂
