### ISSUE TITLE
Add support for forcing the deletion of a directory

### ISSUE THREAD

**Issue by stack72** [joyent/triton-go#60]
When trying to delete a directory, and that directory is not empty, we should add an ability to force that behaviour so that clients do not have to implement looping logic

This will remove things like this

```
Error executing DeleteObject request: DirectoryNotEmpty: /account_name/stor/test-bucket/foo is not empty
```

**Comment by cheapRoc** [comment]
Offline we tossed around a few ideas regarding API. Did we end up agreeing on adding 'Force: true' option for `DeleteDirectoryInput`?
