### ISSUE TITLE
Travis integration for triton-go contribs

### ISSUE THREAD

**Issue by cheapRoc** [joyent/triton-go#7]
What do we need to get this hooked up to Travis? I tried to start that process myself but didn't have "admin" rights. Unsure what needs to be done from here.

/cc @misterbisson @tgross

**Comment by cheapRoc** [comment]
@tgross gave me rights, I'll include the remaining config shortly.

**Comment by cheapRoc** [comment]
I've got a `makefile` started for basic dev/test tooling. It would be worth including for the linter once either myself or someone can get begin documenting the API. Also, I'd like to setup live acceptance tests off master when I get a chance to set up an encrypted key within Travis (if thats possible and/or reasonable).

Keeping this open for the time being then....

**Comment by jen20** [comment]
We need to decouple the account SSH key notifications from my email before this happens ;-)

**Comment by cheapRoc** [comment]
Yeah, we definitely need to discuss to see what options we have.

**Comment by misterbisson** [comment]
Let's add this to our internal CI instead.

**Comment by jen20** [comment]
@misterbisson does our internal CI have the ability to push out build statuses etc?

**Comment by misterbisson** [comment]
Whatever Jenkins plugins we want ;-)

**Comment by cheapRoc** [comment]
I think the thought was whether we can report public build status though a firewall or something...

**Comment by misterbisson** [comment]
> push out build statuses

> whether we can report public build status though a firewall

A typically Joyent way of doing it would be to write the status out to a public directory in Manta, something in a directory like http://us-east.manta.joyent.com/productci/public/ci/go-triton, with a [snaplink](https://apidocs.joyent.com/manta/#snaplinks) for `latest` in addition to directories by build number. Though, if we expect to keep history there for more than about 1M builds, we'll need to add a date component or something else to break it up.

I was answering seriously, however. I was thinking of the [published plugin](https://wiki.jenkins-ci.org/display/JENKINS/HTML+Publisher+Plugin). but I'm sure there are more.

I also need to back off my rather casual comment from earlier. I definitely don't want to insist we use Jenkins, or anything internal.

**Comment by cheapRoc** [comment]
Whoops, there's that clean water again... the awesomeness of owning your own public facing object store. 😉 

We do want to put `triton-go` through secure regression testing. What would be the best way to dog food our own API tooling against live endpoints? I think the internal Jenkins for that sort of test phase would be compatible while also (future) exercising of things such as `triton-go` using mocked-out unit testing via Travis.

**Comment by misterbisson** [comment]
> We do want to put `triton-go` through secure regression testing.

s/want/need/

We can test inside the same account that Jenkins is running in, or continue to use the test account that @jen20 has been using all along.

**Comment by stack72** [comment]
For now, until we have our own infra in place, we added a travis integration just for `go vet` and unit tests

This will be revisited with our own infra later
